CREATE TABLE IF NOT EXISTS Bestellungen (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kaffeeart VARCHAR NOT NULL,
    mitmilch BOOLEAN NOT NULL,
    preis DECIMAL REAL NOT NULL,
    zeitstempel TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Zahlungen (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bestellung_id FOREIGN KEY REFERENCES BESTELUNGEN(ID),
    muenztyp DECIMAL NOT NULL,
    anzahl INTEGER NOT NULL,
);

CREATE TABLE IF NOT EXISTS MUENZENBESTAND (
    muenztyp DECIMAL PRIMARY KEY,
    anzahl INTEGER NOT NULL
);